### PR TITLE
Are minutes ok in md format

### PR DESCRIPTION
**Pull request by hockeyj85**
What
====

This pull request has been opened to discuss whether or not markdown is suitable for our meeting minutes.

Also, pull requests are probably the way that code should be introduced to our master branch, so this is a good introduction for anyone that has not used them before.

One document has been ported to markdown. What are the opinions of the group?

Pros
====

* Can view online
* Can edit online
* Source looks like document
* Formatting is dependent/chosen on how the document is processed

Cons
====

* Looks like Github flavored markdown doesn't handle lists nested 3 times, and it likes to render nested ordered lists as roman numerals.
* We don't know Michael's opinion on markdown.
* Need to run it through a processor if we want to export to html or pdf.

### CODE REVIEW

**Comment by hockeyj85** [comment]
Click on the `files changed` tab to view the diff (containing the md source), if you click `view` at the top right of the source you will see how github renders it.

**Comment by IrascorErgoSum** [comment]
Given that Michael said that the minutes did not need to be in any particularly formal layout, I think "logically laid out" and "readable" are the main concerns - I feel that the pros outweigh the cons significantly, and will be porting our previous minutes.

(commenting here for a paper trail for everyone to follow, eheheheh)

**Comment by hockeyj85** [comment]
:+1:

**Comment by hockeyj85** [comment]
hfd

**Pull request closed without merging**
